services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    #TODO: add a volume for persistent database
    #TODO: later add a dump to start with minimal data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
     - "db"

  front:
    build: ../front/docker/
    restart: always
    volumes:
      - ../front/src/app:/var/www
    depends_on:
      - "back"
    environment:
      BUILD: "prod"
    
  back:
    build: ../back/docker
    restart: always
    volumes:
      - ../back/app:/app
    ports:
      - 3000:3000
    expose:
      - 3000:3000
    depends_on:
      - "db"

  proxy:
    build: ../proxy/docker
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
#     - "back"
      - "front"
      - "db"
